### ISSUE TITLE
Add Regex-based parsers?

### ISSUE THREAD

**Issue by ianmackenzie** [elm-tools/parser#15]
I'm using `elm-tools/parser` to try to parse large machine-generated files in [STEP](https://en.wikipedia.org/wiki/ISO_10303-21) format. To get good parsing performance I've had to use a bunch of tricks like stripping out whitespace using regular expressions as a preprocessing step so that the 'actual' parsing can disregard whitespace. I've also avoided using any of the `Char -> Bool` predicate-based parsers since they seem quite slow compared to `String`-based ones like `symbol` and `ignoreUntil`.

It would be useful for performance (and perhaps convenience in some cases) to have `Regex`-based parsers like

```elm
regex : Regex -> Parser String
ignoreUntilRegex : Regex -> Parser ()
```

For example, right now replicating a hypothetical `Parser.regex (Regex.regex "[A-Z_][A-Z_0-9]")` is possible using the `Parser` module but involves a lot of use of character predicates and is quite slow as a result. Would it be possible to implement one or both of the above without sacrificing too much error message quality? (I'm not as concerned about error message quality myself since the text I care about is machine generated, but I agree that's an extremely important goal in general.)

**Comment by pbiggar** [comment]
I have a similar problem. There are matches I want to support that are relatively complex to represent in the combinators that this parser allows. As an example, here is the regex that represents a JS string: `/"(?:[^\"\\]|\\.)*"/`

~~I tried to build this myself, but none of the things I need to build a Parser are exposed (I was missing Good, Bad, and some other things).~~ They're in a different module, whoops.

**Comment by pbiggar** [comment]
So this is my hacky inefficient way of doing this (fine for my purposes, I'm parsing very very short strings).

```
import Parser exposing (Parser, (|.), (|=), succeed, symbol, float, ignore, zeroOrMore, oneOf, lazy, keep, repeat)
import Parser.Internal as PInternal exposing (Step(..))

token : (String -> a) -> String -> Parser a
token ctor re =
  PInternal.Parser <| \({ source, offset, indent, context, row, col } as state) ->
    let substring = String.dropLeft offset source in
    case Regex.find (Regex.AtMost 1) ("^" ++ re |> Regex.regex) substring of
      [{match}] -> Good (ctor match) { state | offset = offset + String.length match }
      [] -> Bad (Parser.Parser.Fail <| "Regex /" ++ re ++ "/ not matched") state
      _ -> Debug.crash <| "Should never get more than 1 match for regex: " ++ re
```

**Comment by evancz** [comment]
> It would be useful for performance.

I don't think this claim can stand without evidence.

For example, we have recently found that the runtime representation of `Char` in 0.18 causes deoptimization. We distinguish between strings and chars by putting a char in `new String()` which it turns out has a very significant overhead.

There are two ways to address that concern.

  1. Find a better runtime representation. With `Basics.toString` moving to `Debug.toString` we do not need to be able to pretty print chars when we are running in "production" mode, so we can just do the fast thing in that case.
  2. We can find another way to distinguish strings and chars in JavaScript that has better performance. In a past release I would add an `char.isChar = true` field to characters to do this. I do not have the numbers to verify that this is faster or slower though.

So I think this path should be explored thoroughly before seriously considering introducing JS regex. From my testing, JS regex are actually quite slow compared to the implementation strategy that I used for `symbol` and other `String` based parsers. So my sense is that they are slower and worse than the options available to us.

**Comment by ianmackenzie** [comment]
Looking forward to trying out `Parser` again in 0.19 then! I mean, if you did want some hard numerical evidence I could provide actual before and after timings for the regex-based optimizations I mentioned in the original issue text (and for the additional roughly 2x speedup I just recently got by converting my remaining `Parser`-based code over to a hand-rolled `Regex`-based solution). But if some `Char` optimizations make the `Parser`s as fast or faster than a regex then that is a vastly better solution!

**Comment by pbiggar** [comment]
I commented on this issue not because of performance, but because tokenizing using regex is a much simpler way of making parsers relative to what's in the library right now.

@evancz You closed this - would you prefer I make a new issue for the non-performance-related reasons to have regex parsers?

**Comment by evancz** [comment]
Yes, ideally people would never tag onto existing issues. Instead it is better to explain the issue separately on its own terms. This makes it much easier to review different requests without tangling people's problems together.

I don't know what you are saying, so try to make an http://sscce.org/ in a stand-alone issue.

You should outline your need as clearly as possible *without* talking about the proposed regex solution. It may be that there are primitives that make it easier, and no one can assess that if there is only a feature request without other details.
