### ISSUE TITLE
It's awkward to require at most n characters

### ISSUE THREAD

**Issue by BrianHicks** [elm-tools/parser#20]
Most of the block-level constructs in commonmark allow up to three characters of space before the start of the element. For example, `···#·hello` is still `<h1>hello</h1>`. This is specifically 3 because 4 or more is the start of a code element. (`····hello` == `<pre><code>hello</pre></code>`)

To parse this, I have the following:

```elm
{-| Most of the CommonMark block elements allow one to three spaces before the
beginning of the block. So, helper parser!
-}
oneToThreeSpaces : Parser ()
oneToThreeSpaces =
    oneOf
        [ symbol "   "
        , symbol "  "
        , symbol " "
        , succeed ()
        ]
```

But it's kind of awkward to write like that. I'd rather write something like this:

```elm
{-| Most of the CommonMark block elements allow one to three spaces before the
beginning of the block. So, helper parser!
-}
oneToThreeSpaces : Parser ()
oneToThreeSpaces =
    ignore (AtMost 3) ((==) ' ')
```

**Comment by pablohirafuji** [comment]
Couldn't you use [getIndentLevel](http://package.elm-lang.org/packages/elm-tools/parser/2.0.1/Parser-LowLevel#getIndentLevel)? I think that's also going to be useful when parsing lists inside lists inside lists...

**Comment by oldfartdeveloper** [comment]
@BrianHicks I've been "stuck" on the same issue, and I woke up at 4:00 AM with this workaround:

```elm
oneOf [
    keep (Exactly 3) (\c -> c == ' ')
  , keep oneOrMore (\c -> c == ' ')
]
```
 
The first `keep` succeeds if it can grab the maximum number of spaces you are looking for.
Otherwise it will grab what it can in the 2nd `keep`.

An advantage is that this solution prevents the potential "buffer-busting" outcome of using just `oneOrMore` when a hacker might attempt to shove thousands of space characters.

I like your proposal, but until something like it is implemented, this might be suitable.

I have a similar situation in which I need to grab from 1 to 6 digits.

HTH

**Comment by evancz** [comment]
I think you can write helpers for cases like this:

```elm
atMost : Int -> Parser () -> Parser ()
atMost n parser =
  if n <= 0 then
    succeed ()
  else
    oneOf
      [ map2 always parser (atMost (n - 1) parser)
      , succeed ()
      ]
```

It may be worth adding examples of a bunch of different things like this, but I hesitate to put them in the API directly. Maybe I can add things to `examples/` and see how useful they are to folks.
